---
title: "Kevin Jose Guzman, MD"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

## About myself 

Hello! My name is Kevin Jose Guzman, and I am a data enthusiast with a passion for uncovering insights through data analysis and visualization. 

I am a pulmonary and critical care physician by training and currently hold an appointment at Columbia Univeristy Irving Medical Center. My passions are to use data to improve health care systems. Currently, I my work focuses on multidrug-resistant tuberculosis and HIV, where I seek to uncover patterns in order to improve the treatments we deliver. 

## My projects 

My projects currently include using latent class analysis, latent class growth analysis, and machine learning techniques to predict treatment outcomes in people living with MDR-TB/HIV. I also work with my PI in New York City on a project to improve screening approaches for active tuberculosis in migrant populations.

## Professional Appointment 

I am also currently a member of the American Throacic Society Diversity, Equity, and Inclusion Committee. 

## Learn More About My Professional Experience
* [Professional Experience](professional.html)

## Problem Number 2 
* [Problem Number 2](problem2.html)
