---
title: "Problem 2"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Load necessary libraries
library(tidyverse)
library(plotly)
library("p8105.datasets")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Load Instacart dataset
data("instacart")
```

## Bar chart 
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Creating a subset
bar_subset <- instacart %>%
  filter(aisle=="fresh herbs") %>% 
  select(product_name, order_number) %>%   
  drop_na(order_number) %>% 
  group_by(product_name) %>% 
  summarise(total_orders = n()) %>% 
  ungroup()

# Bar chart 
bar_chart <- plot_ly(bar_subset, 
                     x = ~product_name, 
                     y = ~total_orders, 
                     type = 'bar') %>%
  layout(title = "Fresh Herbs Sold by Number",
         xaxis = list(title = "Product Name"),
         yaxis = list(title = "Total Orders"),
         barmode = 'stack') 
bar_chart
```

## Box Plot
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Number of Products Ordered by Time of day box
box_subset <- instacart %>% 
  select(order_id, order_hour_of_day) %>% 
  drop_na(order_hour_of_day) %>% 
  group_by(order_id, order_hour_of_day) %>% 
  summarise(total_number = n()) %>% 
  ungroup()

#Scatter plot
box_plot <- plot_ly(box_subset, 
                       x=~order_hour_of_day,
                       y=~total_number,
                       type='box') %>% 
  layout(title = "Number of Items Ordered by Hour of Day",
         xaxis = list(title = "Hour of Day"),
         yaxis = list(title = "Number of Items per Customer")) 

box_plot
```

## Waterfall
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Number of Products Ordered by Time of day waterfall
waterfall_subset <- instacart %>% 
  select(aisle) %>% 
  drop_na(aisle) %>% 
  group_by(aisle) %>% 
  summarise(total_number=n()) %>% 
  ungroup

# Bubble plot
waterfall_plot <- plot_ly(waterfall_subset,
                       x=~aisle, 
                       y=~total_number,
                       type='waterfall') %>% 
   layout(title = "Number of Items Ordered by Type",
         xaxis = list(title = "Item"),
         yaxis = list(title = "Number of Items Ordered")) 

waterfall_plot
```